conventional-commits:
  - type: Maintenance work
    nouns: [chore, doc, docs, release]
    labels: [conventional-commit/chore]
  - type: New feature
    nouns: [feat]
    labels: [conventional-commit/feat]
  - type: Bug fix
    nouns: [fix]
    labels: [conventional-commit/fix]
