# yaml-language-server: $schema=https://json.schemastore.org/golangci-lint.json
linters:
  disable-all: true
  enable:
  - gofmt
  - goimports
  - revive
linters-settings:
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        disabled: true
