version: "2"

linters:
  default: none
  enable:
    - misspell
    - perfsprint
    - revive
    - testifylint

  settings:
    perfsprint:
      integer-format: true
      int-conversion: true
      error-format: true
      err-error: false
      errorf: true
      string-format: true
      sprintf1: true
      strconcat: true
      bool-format: true
      hex-format: true

    revive:
      enable-all-rules: false
      rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
        - name: blank-imports
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#argument-limit
        - name: argument-limit
          arguments: [5]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#atomic
        - name: atomic
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#confusing-results
        - name: confusing-results
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
        - name: context-as-argument
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#datarace
        - name: datarace
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#defer
        - name: defer
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
        - name: dot-imports
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#duplicated-imports
        - name: duplicated-imports
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
        - name: early-return
          arguments: [preserveScope]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-block
        - name: empty-block
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
        - name: empty-lines
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-map-style
        - name: enforce-map-style
          arguments: [make]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-repeated-arg-type-style
        - name: enforce-repeated-arg-type-style
          arguments: [full]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#enforce-slice-style
        - name: enforce-slice-style
          arguments: [make]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-naming
        - name: error-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
        - name: error-return
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
        - name: error-strings
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf
        - name: errorf
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#get-return
        - name: get-return
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#identical-branches
        - name: identical-branches
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
        - name: if-return
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#import-alias-naming
        - name: import-alias-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#imports-blocklist
        - name: imports-blocklist
          arguments: ["gotest.tools/v3/assert"] # IDE auto-inserted instead of testify's assert
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#increment-decrement
        - name: increment-decrement
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow
        - name: indent-error-flow
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#max-control-nesting
        - name: max-control-nesting
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#modifies-value-receiver
        - name: modifies-value-receiver
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#optimize-operands-order
        - name: optimize-operands-order
          exclude: [TEST]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
        - name: range
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#redundant-import-alias
        - name: redundant-import-alias
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#struct-tag
        - name: struct-tag
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#superfluous-else
        - name: superfluous-else
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unchecked-type-assertion
        - name: unchecked-type-assertion
          exclude: [TEST]
          arguments: [acceptIgnoredAssertionResult: true]
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-naming
        - name: unexported-naming
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
        - name: unhandled-error
          exclude: [TEST]
          arguments:
            - "^fmt.Print"
            - "^fmt.Println"
            - "^fmt.Fprintf"
            - "^fmt.Fprintln"
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt
        - name: unnecessary-stmt
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unreachable-code
        - name: unreachable-code
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
        - name: unused-receiver
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any
        - name: use-any
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#useless-break
        - name: useless-break
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-declaration
        - name: var-declaration
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#waitgroup-by-value
        - name: waitgroup-by-value
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

run:
  build-tags: [integration]
