// Code generated by "-i yaml/*.yml -p builtin -o ./generated.go"; DO NOT EDIT.

package builtin

import (
	injector "github.com/datadog/orchestrion/internal/injector"
	advice "github.com/datadog/orchestrion/internal/injector/advice"
	code "github.com/datadog/orchestrion/internal/injector/advice/code"
	join "github.com/datadog/orchestrion/internal/injector/join"
)

var Aspects = [...]injector.Aspect{
	// From yaml/chi.yml
	{
		JoinPoint: join.AssignmentOf(join.FunctionCall("github.com/go-chi/chi/v5.NewRouter")),
		Advice: []advice.Advice{
			advice.AddComment("//dd:instrumented"),
			advice.AppendStatements(code.MustTemplate(
				"{{.Assignment.Variable}}.Use(instrument.ChiV5Middleware())",
				map[string]string{
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
	// From yaml/dd-span.yml
	{
		JoinPoint: join.FunctionBody(join.Function(
			join.Receives(join.MustTypeName("context.Context")),
			join.Directive("dd:span"),
		)),
		Advice: []advice.Advice{
			advice.PrependStmts(code.MustTemplate(
				"{{$ctx := .FindArgument \"context.Context\"}}{{$name := .Function.Name}}instrument.Report({{$ctx}}, event.EventStart{{with $name}}, \"name\", {{printf \"%q\" .}}{{end}}{{range .DirectiveArgs \"dd:span\"}}, {{printf \"%q\" .Key}}, {{printf \"%q\" .Value}}{{end}})\ndefer instrument.Report({{$ctx}}, event.EventEnd{{with $name}}, \"name\", {{printf \"%q\" .}}{{end}}{{range .DirectiveArgs \"dd:span\"}}, {{printf \"%q\" .Key}}, {{printf \"%q\" .Value}}{{end}})",
				map[string]string{
					"event":      "github.com/datadog/orchestrion/instrument/event",
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
	// From yaml/echo.yml
	{
		JoinPoint: join.AssignmentOf(join.FunctionCall("github.com/labstack/echo/v4.New")),
		Advice: []advice.Advice{
			advice.AddComment("//dd:instrumented"),
			advice.AppendStatements(code.MustTemplate(
				"{{.Assignment.Variable}} = {{.Assignment.Variable}}.Use(instrument.EchoV4Middleware())",
				map[string]string{
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
	// From yaml/fiber.yml
	{
		JoinPoint: join.AssignmentOf(join.FunctionCall("github.com/gofiber/fiber/v2.New")),
		Advice: []advice.Advice{
			advice.AddComment("//dd:instrumented"),
			advice.AppendStatements(code.MustTemplate(
				"{{.Assignment.Variable}}  = {{.Assignment.Variable}}.Use(instrument.FiberMiddleware())",
				map[string]string{
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
	// From yaml/grpc.yml
	{
		JoinPoint: join.FunctionCall("google.golang.org/grpc.Dial"),
		Advice: []advice.Advice{
			advice.AppendArgs(
				code.MustTemplate(
					"instrument.GRPCStreamClientInterceptor()",
					map[string]string{
						"instrument": "github.com/datadog/orchestrion/instrument",
					},
				),
				code.MustTemplate(
					"instrument.GRPCUnaryClientInterceptor()",
					map[string]string{
						"instrument": "github.com/datadog/orchestrion/instrument",
					},
				),
			),
		},
	},
	{
		JoinPoint: join.FunctionCall("google.golang.org/grpc.NewServer"),
		Advice: []advice.Advice{
			advice.AppendArgs(
				code.MustTemplate(
					"instrument.GRPCStreamServerInterceptor()",
					map[string]string{
						"instrument": "github.com/datadog/orchestrion/instrument",
					},
				),
				code.MustTemplate(
					"instrument.GRPCUnaryServerInterceptor()",
					map[string]string{
						"instrument": "github.com/datadog/orchestrion/instrument",
					},
				),
			),
		},
	},
	// From yaml/net-http.yml
	{
		JoinPoint: join.StructLiteral(join.MustTypeName("net/http.Server"), "Handler"),
		Advice: []advice.Advice{
			advice.WrapExpression(code.MustTemplate(
				"//dd:startwrap\ninstrument.WrapHandler({{.}})\n//dd:endwrap",
				map[string]string{
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
	{
		JoinPoint: join.FunctionBody(join.Function(
			join.Signature(
				[]join.TypeName{join.MustTypeName("net/http.ResponseWriter"), join.MustTypeName("*net/http.Request")},
				nil,
			),
		)),
		Advice: []advice.Advice{
			advice.PrependStmts(code.MustTemplate(
				"{{$arg := .Function.Argument 1}}{{$name := .Function.Name}}instrument.Report({{$arg}}.Context(), instrument.EventStart{{with $name}}, \"name\", {{printf \"%q\" .}}{{end}}, \"verb\", {{$arg}}.Method{{range .DirectiveArgs \"dd:span\"}}, {{printf \"%q\" .Key}}, {{printf \"%q\" .Value}}{{end}}))\ndefer instrument.Report({{$arg}}.Context(), instrument.EventEnd{{with $name}}, \"name\", {{printf \"%q\" .}}{{end}}, \"verb\", {{$arg}}.Method{{range .DirectiveArgs \"dd:span\"}}, {{printf \"%q\" .Key}}, {{printf \"%q\" .Value}}{{end}}))",
				map[string]string{
					"instrument": "github.com/datadog/orchestrion/instrument",
				},
			)),
		},
	},
}
