// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by "github.com/datadog/orchestion/internal/injector/builtin/generator -i yaml/*.yml -i yaml/*/*.yml -p builtin -o ./generated.go -d ./generated_deps.go -C 1 -docs ../../../docs/content/docs/built-in/"; DO NOT EDIT.

//go:build tools

package builtin

import (
	_ "github.com/datadog/orchestrion/instrument"
	_ "github.com/datadog/orchestrion/instrument/event"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/gin-gonic/gin"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/go-chi/chi.v5"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/gofiber/fiber.v2"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/google.golang.org/grpc"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
	_ "gopkg.in/DataDog/dd-trace-go.v1/contrib/labstack/echo.v4"
	_ "gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)
