// Code generated by "stringer -type=Event"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventStart-1]
	_ = x[EventEnd-2]
	_ = x[EventCall-3]
	_ = x[EventReturn-4]
	_ = x[EventDBCall-5]
	_ = x[EventDBReturn-6]
}

const _Event_name = "EventStartEventEndEventCallEventReturnEventDBCallEventDBReturn"

var _Event_index = [...]uint8{0, 10, 18, 27, 38, 49, 62}

func (i Event) String() string {
	i -= 1
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
