// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.

package main

import (
	"crypto/sha512"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"gopkg.in/yaml.v3"
)

type globs []string

func main() {
	var (
		pkg           string
		glob          globs
		deps          string
		docsDir       string
		schemadocsDir string
		chomp         int
	)

	flag.StringVar(&pkg, "p", "", "package name")
	flag.Var(&glob, "i", "input files (glob syntax, can be set multiple times)")
	flag.StringVar(&deps, "d", "", "dependencies file")
	flag.StringVar(&docsDir, "docs", "", "directory to write documentation files to")
	flag.StringVar(&schemadocsDir, "schemadocs", "", "directory to write schema documentation files to")
	flag.IntVar(&chomp, "C", 0, "number of leading path components to strip from matched file names")
	flag.Parse()

	if len(glob) == 0 {
		log.Fatalln("Missing -i option!")
	}

	if schemadocsDir != "" {
		if err := documentSchema(schemadocsDir); err != nil {
			log.Fatalln(err)
		}
	}

	matches, err := glob.glob()
	if err != nil {
		log.Fatalf("failed to process glob pattern(s) %s: %v\n", glob, err)
	}

	if len(matches) == 0 {
		log.Fatalf("no files matched pattern %q\n", glob)
	}
	// Ensure the files are sorted for determinism.
	sort.Strings(matches)

	docsToDelete := make(map[string]struct{})
	if docsDir != "" {
		filepath.WalkDir(docsDir, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() || filepath.Ext(path) != ".md" || strings.HasPrefix(filepath.Base(path), "_") {
				return nil
			}
			docsToDelete[path] = struct{}{}
			return nil
		})
		defer func() {
			// On exiting, remove no longer needed files
			for path := range docsToDelete {
				if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
					log.Fatalf("Failed to delete old file %q: %v\n", path, err)
				}
			}
		}()
	}

	var (
		depsFile      *jen.File
		injectedPaths = make(map[string]struct{})
	)
	if deps != "" {
		depsFile = jen.NewFile(pkg)
		depsFile.HeaderComment("Unless explicitly stated otherwise all files in this repository are licensed")
		depsFile.HeaderComment("under the Apache License Version 2.0.")
		depsFile.HeaderComment("This product includes software developed at Datadog (https://www.datadoghq.com/).")
		depsFile.HeaderComment("Copyright 2023-present Datadog, Inc.")
		depsFile.HeaderComment("")
		depsFile.HeaderComment(fmt.Sprintf("Code generated by %q; DO NOT EDIT.", "github.com/DataDog/orchestion/internal/injector/builtin/generator "+strings.Join(os.Args[1:], " ")))
		depsFile.PackageComment("//go:build tools")
	}

	checksum := sha512.New()
	for _, match := range matches {
		// Checksum header -- SOH <relative file name> STX
		writeAll(checksum, []byte(fmt.Sprintf("\x01%s\x02", match)))

		data, err := os.ReadFile(match)
		if err != nil {
			log.Fatalf("failed to read input file %q: %v\n", match, err)
		}

		if err := validateSchema(data); err != nil {
			log.Fatalf("failed to validate contents of %q: %v\n", match, err)
		}

		// Checksum body -- <data> ETX
		writeAll(checksum, data)
		writeAll(checksum, []byte{'\x03'})

		var config ConfigurationFile
		if err := yaml.Unmarshal(data, &config); err != nil {
			log.Fatalf("failed to unmarshal input file %q: %v\n", match, err)
		}

		chomped := removeLeadingSegments(match, chomp)

		if docsDir != "" {
			filename, err := documentConfiguration(docsDir, chomped, &config)
			if err != nil {
				log.Fatalf("failed to document aspects from %q: %v\n", match, err)
			}
			delete(docsToDelete, filename)
		}

		for _, entry := range config.Aspects {
			if depsFile != nil {
				// Make sure all necessary packages are tracked
				imports := entry.Aspect.AddedImports()
				depsFile.Anon(imports...)
				for _, path := range imports {
					injectedPaths[path] = struct{}{}
				}
			}
		}
	}

	if depsFile != nil {
		if err := depsFile.Save(deps); err != nil {
			log.Fatalf("Error writing output file %q: %v\n", deps, err)
		}
	}
}

func writeAll(w io.Writer, data []byte) {
	for len(data) > 0 {
		n, err := w.Write(data)
		if err != nil {
			log.Fatalf("Failed while computing checksum: %v\n", err)
		}
		data = data[n:]
	}
}

func init() {
	log.SetPrefix("github.com/DataDog/orchestrion/internal/injector/builtin/generate: ")
}

func (g *globs) Set(value string) error {
	*g = append(*g, value)
	return nil
}

func (g *globs) String() string {
	return strings.Join(*g, " ")
}

func (g *globs) glob() (files []string, err error) {
	unique := make(map[string]struct{})
	for _, pattern := range *g {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return nil, err
		}
		for _, match := range matches {
			if _, found := unique[match]; found {
				continue
			}
			unique[match] = struct{}{}
			files = append(files, match)
		}
	}

	if len(files) == 0 {
		err = fmt.Errorf("no files matched pattern(s) %s", g)
	}

	// Ensure output is sorted for determinism...
	sort.Strings(files)

	return
}

func removeLeadingSegments(path string, n int) string {
	if n <= 0 {
		return path
	}
	sep := string(filepath.Separator)
	parts := strings.Split(path, sep)
	if len(parts) <= n {
		return path
	}
	return strings.Join(parts[n:], sep)
}
