// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

//go:build integration

package awsv2

import (
	"datadoghq.dev/orchestrion/_integration-tests/utils"
	"testing"
)

func TestIntegration_awsv2_LoadDefaultConfig(t *testing.T) {
	utils.RunTest(t, new(TestCaseLoadDefaultConfig))
}

func TestIntegration_awsv2_NewConfig(t *testing.T) {
	utils.RunTest(t, new(TestCaseNewConfig))
}

func TestIntegration_awsv2_StructLiteral(t *testing.T) {
	utils.RunTest(t, new(TestCaseStructLiteral))
}

func TestIntegration_awsv2_StructLiteralPtr(t *testing.T) {
	utils.RunTest(t, new(TestCaseStructLiteralPtr))
}
