name: Upload coverage report to CodeCov
description: Upload the provided code coverage report(s) to CodeCov
inputs:
  name:
    description: Name of the upload (visible in CodeCov)
    required: true
  flags:
    description: Flags to assign to the upload
    required: true
  files:
    description: Files to upload
    required: true
  token:
    description: CodeCov token to use
    required: true
runs:
  using: composite
  steps:
    - name: Install CodeCov CLI
      id: codecov-cli
      uses: ./.github/actions/codecov-cli
    - name: Upload coverage report
      shell: bash
      env:
        CODECOV_TOKEN: ${{ inputs.token }}
        FILES: ${{ inputs.files }}
        FLAGS: ${{ inputs.flags }}
      run: |-
        set -euo pipefail
        pr=()
        sha="${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          pr+=("--pr=${{ github.event.number }}")
        fi

        file=()
        for f in ${FILES}; do
          file+=("--file=${f}")
        done

        flag=()
        for f in ${FLAGS}; do
          flag+=("--flag=${f}")
        done

        ${{ steps.codecov-cli.outputs.codecov }}                                \
          --auto-load-params-from=GithubActions                                 \
          --verbose                                                             \
          do-upload                                                             \
          --disable-search                                                      \
          ${file[@]+"${file[@]}"}                                               \
          --name="${{ inputs.name }}"                                           \
          ${pr[@]+"${pr[@]}"}                                                   \
          ${flag[@]+"${flag[@]}"}                                               \
          --sha="${sha}"                                                        \
          --fail-on-error                                                       \
          --git-service=github                                                  \
          --token="${CODECOV_TOKEN}"                                            \
          --slug="${{ github.repository }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4
      with:
        name: ${{ inputs.name }} coverage report
        path: ${{ inputs.files }}
