// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.

// Code generated by `orchestrion pin`; DO NOT EDIT.

// This file is generated by `orchestrion pin`, and is used to include a blank import of the
// orchestrion package(s) so that `go mod tidy` does not remove the requirements from go.mod.
// This file should be checked into source control.

//go:build tools

package tools

import _ "github.com/datadog/orchestrion"
