// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

//go:build integration

package nethttp

import (
	"testing"

	"datadoghq.dev/orchestrion/_integration-tests/utils"
)

func TestClientError(t *testing.T) {
	utils.RunTest(t, new(TestCaseClientError))
}

func TestFuncHandler(t *testing.T) {
	utils.RunTest(t, new(TestCaseFuncHandler))
}

func TestHandlerImplementation(t *testing.T) {
	utils.RunTest(t, new(TestCaseHandlerImplementation))
}

func TestHandlerIsNil(t *testing.T) {
	utils.RunTest(t, new(TestCaseHandlerIsNil))
}

func TestIssue400(t *testing.T) {
	utils.RunTest(t, new(TestCaseIssue400))
}

func TestServeMuxHandler(t *testing.T) {
	utils.RunTest(t, new(TestCaseServeMuxHandler))
}
