// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

//go:build integration

package nethttp

import (
	"datadoghq.dev/orchestrion/_integration-tests/utils"
	"testing"
)

func TestIntegration_nethttp_FuncHandler(t *testing.T) {
	utils.RunTest(t, new(TestCaseFuncHandler))
}

func TestIntegration_nethttp_HandlerImplementation(t *testing.T) {
	utils.RunTest(t, new(TestCaseHandlerImplementation))
}

func TestIntegration_nethttp_Issue400(t *testing.T) {
	utils.RunTest(t, new(TestCaseIssue400))
}

func TestIntegration_nethttp_ServeMuxHandler(t *testing.T) {
	utils.RunTest(t, new(TestCaseServeMuxHandler))
}
