// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/datadog/orchestrion/internal/injector"
	"github.com/dave/jennifer/jen"
	"gopkg.in/yaml.v3"
)

func main() {
	var (
		pkg    string
		glob   string
		output string
	)

	flag.StringVar(&pkg, "p", "", "package name")
	flag.StringVar(&glob, "i", "", "input files (glob syntax)")
	flag.StringVar(&output, "o", "", "output file")
	flag.Parse()

	matches, err := filepath.Glob(glob)
	if err != nil {
		log.Fatalf("failed to process glob pattern %q: %v", glob, err)
	}

	if len(matches) == 0 {
		log.Fatalf("no files matched pattern %q", glob)
	}

	file := jen.NewFile(pkg)
	file.HeaderComment("Unless explicitly stated otherwise all files in this repository are licensed")
	file.HeaderComment("under the Apache License Version 2.0.")
	file.HeaderComment("This product includes software developed at Datadog (https://www.datadoghq.com/).")
	file.HeaderComment("Copyright 2023-present Datadog, Inc.")
	file.HeaderComment("")
	file.HeaderComment(fmt.Sprintf("Code generated by %q; DO NOT EDIT.", "github.com/datadog/orchestion/internal/injector/builtin/generate "+strings.Join(os.Args[1:], " ")))

	file.Var().Id("Aspects").Op("=").Index(jen.Op("...")).Qual("github.com/datadog/orchestrion/internal/injector", "Aspect").ValuesFunc(func(g *jen.Group) {
		for _, match := range matches {
			data, err := os.ReadFile(match)
			if err != nil {
				log.Fatalf("failed to read input file %q: %v", match, err)
			}

			var aspects []injector.Aspect
			if err := yaml.Unmarshal(data, &aspects); err != nil {
				log.Fatalf("failed to unmarshal input file %q: %v", match, err)
			}

			for i, aspect := range aspects {
				item := g.Line()
				if i == 0 {
					item = item.Commentf("From %s", match).Line()
				}
				jp, adv := aspect.AsCode()
				item.Values(
					jen.Line().Id("JoinPoint").Op(":").Add(jp),
					jen.Line().Id("Advice").Op(":").Add(adv),
					jen.Line().Empty(),
				)
			}
		}
		g.Empty().Line()
	})

	if err := file.Save(output); err != nil {
		log.Fatalf("Error writing output file %q: %v", output, err)
	}
}

func init() {
	log.SetPrefix("github.com/DataDog/orchestrion/internal/injector/builtin/generate: ")
}
