// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.

// Code generated by 'go generate' DO NOT EDIT.

package proxy

import "flag"

func (f *compileFlagSet) parse(args []string) ([]string, error) {
	flagSet := flag.NewFlagSet("compile", flag.ContinueOnError)
	flagSet.Bool("%", false, "debug non-static initializers")
	flagSet.Bool("+", false, "compiling runtime")
	flagSet.Bool("B", false, "disable bounds checking")
	flagSet.Bool("C", false, "disable printing of columns in error messages")
	flagSet.String("D", "", "set relative path for local imports")
	flagSet.Bool("E", false, "debug symbol export")
	flagSet.String("I", "", "add directory to import search path")
	flagSet.Bool("K", false, "debug missing line numbers")
	flagSet.Bool("L", false, "also show actual source file names in error messages for positions affected by //line directives")
	flagSet.Bool("N", false, "disable optimizations")
	flagSet.Bool("S", false, "print assembly listing")
	flagSet.BoolFunc("V", "print version and exit", func(string) error {
		f.ShowVersion = true
		return nil
	})
	flagSet.Bool("W", false, "debug parse tree after type checking")
	flagSet.Bool("asan", false, "build code compatible with C/C++ address sanitizer")
	flagSet.String("asmhdr", "", "write assembly header to file")
	flagSet.String("bench", "", "append benchmark times to file")
	flagSet.String("blockprofile", "", "write block profile to file")
	flagSet.String("buildid", "", "record id as the build id in the export metadata")
	flagSet.Int("c", 4, "concurrency during compilation (1 means no concurrency)")
	flagSet.Bool("clobberdead", false, "clobber dead stack slots (for debugging)")
	flagSet.Bool("clobberdeadreg", false, "clobber dead registers (for debugging)")
	flagSet.Bool("complete", false, "compiling complete package (no C or assembly)")
	flagSet.String("coveragecfg", "", "read coverage configuration from file")
	flagSet.String("cpuprofile", "", "write cpu profile to file")
	flagSet.String("d", "", "enable debugging settings; try -d help")
	flagSet.Bool("dwarf", true, "generate DWARF symbols")
	flagSet.Bool("dwarfbasentries", true, "use base address selection entries in DWARF")
	flagSet.Bool("dwarflocationlists", true, "add location lists to DWARF in optimized mode")
	flagSet.Bool("dynlink", false, "support references to Go symbols defined in other shared libraries")
	flagSet.Bool("e", false, "no limit on number of errors reported")
	flagSet.String("embedcfg", "", "read go:embed configuration from file")
	flagSet.String("env", "", "add definition of the form key=value to environment")
	flagSet.Bool("errorurl", false, "print explanatory URL with error message if applicable")
	flagSet.Int("gendwarfinl", 2, "generate DWARF inline info records")
	flagSet.String("goversion", "", "required version of the runtime")
	flagSet.Bool("h", false, "halt on error")
	flagSet.StringVar(&f.ImportCfg, "importcfg", "", "read import configuration from file")
	flagSet.String("installsuffix", "", "set pkg directory suffix")
	flagSet.Bool("j", false, "debug runtime-initialized variables")
	flagSet.String("json", "", "version,file for JSON compiler/optimizer detail output")
	flagSet.Bool("l", false, "disable inlining")
	flagSet.StringVar(&f.Lang, "lang", "", "Go language version source code expects")
	flagSet.String("linkobj", "", "write linker-specific object to file")
	flagSet.Bool("linkshared", false, "generate code that will be linked against Go shared libraries")
	flagSet.Bool("live", false, "debug liveness analysis")
	flagSet.Bool("m", false, "print optimization decisions")
	flagSet.String("memprofile", "", "write memory profile to file")
	flagSet.String("memprofilerate", "", "set runtime.MemProfileRate to rate")
	flagSet.Bool("msan", false, "build code compatible with C/C++ memory sanitizer")
	flagSet.String("mutexprofile", "", "write mutex profile to file")
	flagSet.Bool("nolocalimports", false, "reject local (relative) imports")
	flagSet.StringVar(&f.Output, "o", "", "write output to file")
	flagSet.StringVar(&f.Package, "p", "", "set expected package import path")
	flagSet.Bool("pack", false, "write to file.a instead of file.o")
	flagSet.String("pgoprofile", "", "read profile or pre-process profile from file")
	flagSet.Bool("r", false, "debug generated wrappers")
	flagSet.Bool("race", false, "enable race detector")
	flagSet.Bool("shared", false, "generate code that can be linked into a shared library")
	flagSet.Bool("smallframes", false, "reduce the size limit for stack allocated objects")
	flagSet.String("spectre", "", "enable spectre mitigations in list (all, index, ret)")
	flagSet.Bool("std", false, "compiling standard library")
	flagSet.String("symabis", "", "read symbol ABIs from file")
	flagSet.Bool("t", false, "enable tracing for debugging the compiler")
	flagSet.String("traceprofile", "", "write an execution trace to file")
	flagSet.String("trimpath", "", "remove prefix from recorded source file paths")
	flagSet.Bool("v", false, "increase debug verbosity")
	flagSet.Bool("w", false, "debug type checking")
	flagSet.Bool("wb", true, "enable write barrier")

	err := flagSet.Parse(args)
	return flagSet.Args(), err
}
