// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.)

// Code generated by 'go generate' DO NOT EDIT.

package proxy

import "flag"

func (f *linkFlagSet) parse(args []string) ([]string, error) {
	flagSet := flag.NewFlagSet("link", flag.ContinueOnError)
	flagSet.String("B", "", "add an ELF NT_GNU_BUILD_ID note when using ELF; use \"gobuildid\" to generate it from the Go build ID")
	flagSet.String("E", "", "set entry symbol name")
	flagSet.String("H", "", "set header type")
	flagSet.String("I", "", "use linker as ELF dynamic linker")
	flagSet.String("L", "", "add specified directory to library path")
	flagSet.String("R", "-1", "set address rounding quantum")
	flagSet.Int("T", -1, "set the start address of text symbols")
	flagSet.BoolFunc("V", "print version and exit", func(string) error {
		f.showVersion = true
		return nil
	})
	flagSet.String("X", "", "add string value definition of the form importpath.name=value")
	flagSet.Bool("a", false, "no-op (deprecated)")
	flagSet.Bool("asan", false, "enable ASan interface")
	flagSet.Bool("aslr", true, "enable ASLR for buildmode=c-shared on windows")
	flagSet.String("benchmark", "", "set to 'mem' or 'cpu' to enable phase benchmarking")
	flagSet.String("benchmarkprofile", "", "emit phase profiles to base_phase.{cpu,mem}prof")
	flagSet.Bool("bindnow", false, "mark a dynamically linked ELF object for immediate function binding")
	flagSet.String("buildid", "", "record id as Go toolchain build id")
	flagSet.StringVar(&f.BuildMode, "buildmode", "", "set build mode")
	flagSet.Bool("c", false, "dump call graph")
	flagSet.String("capturehostobjs", "", "capture host object files loaded during internal linking to specified dir")
	flagSet.Bool("checklinkname", true, "check linkname symbol references")
	flagSet.Bool("compressdwarf", true, "compress DWARF if possible")
	flagSet.String("cpuprofile", "", "write cpu profile to file")
	flagSet.Bool("d", false, "disable dynamic executable")
	flagSet.Bool("debugnosplit", false, "dump nosplit call graph")
	flagSet.Int("debugtextsize", 0, "debug text section max size")
	flagSet.Int("debugtramp", 0, "debug trampolines")
	flagSet.Bool("dumpdep", false, "dump symbol dependency graph")
	flagSet.String("extar", "", "archive program for buildmode=c-archive")
	flagSet.String("extld", "", "use linker when linking in external mode")
	flagSet.String("extldflags", "", "pass flags to external linker")
	flagSet.Bool("f", false, "ignore version mismatch")
	flagSet.Bool("g", false, "disable go package data checks")
	flagSet.Bool("h", false, "halt on error")
	flagSet.StringVar(&f.ImportCfg, "importcfg", "", "read import configuration from file")
	flagSet.String("installsuffix", "", "set package directory suffix")
	flagSet.String("k", "", "set field tracking symbol")
	flagSet.String("libgcc", "", "compiler support lib for internal linking; use \"none\" to disable")
	flagSet.String("linkmode", "", "set link mode")
	flagSet.Bool("linkshared", false, "link against installed Go shared libraries")
	flagSet.String("memprofile", "", "write memory profile to file")
	flagSet.String("memprofilerate", "", "set runtime.MemProfileRate to rate")
	flagSet.Bool("msan", false, "enable MSan interface")
	flagSet.Bool("n", false, "no-op (deprecated)")
	flagSet.StringVar(&f.Output, "o", "", "write output to file")
	flagSet.String("pluginpath", "", "full path name for plugin")
	flagSet.Bool("pruneweakmap", true, "prune weak mapinit refs")
	flagSet.String("r", "", "set the ELF dynamic linker search path to dir1:dir2:...")
	flagSet.Bool("race", false, "enable race detector")
	flagSet.Int("randlayout", 0, "randomize function layout")
	flagSet.Bool("s", false, "disable symbol table")
	flagSet.Int("strictdups", 0, "sanity check duplicate symbol contents during object file reading (1=warn 2=err).")
	flagSet.String("tmpdir", "", "use directory for temporary files")
	flagSet.Bool("v", false, "print link trace")
	flagSet.Bool("w", false, "disable DWARF generation")

	err := flagSet.Parse(args)
	return flagSet.Args(), err
}
