name: PR Labeler
on:
  pull_request:
    types: [opened, edited, reopened]
permissions: read-all
jobs:
  update-labels:
    name: Update PR labels
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed to update labels
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5
        with:
          go-version: oldstable
          cache-dependency-path: '**/go.mod'
      - name: Assign Labels
        run: go -C _tools run ./conventionalcommit
        env:
          GITHUB_TOKEN: ${{ github.token }}
