
name: Spelling

on: [push, pull_request]

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Typos
        uses: crate-ci/typos@392b78fe18a52790c53f42456e46124f77346842 # v1.34.0
        with:
          config: ./typos.yaml
