name: Toolexec Tests
on:
  pull_request:
    paths:
      internal/toolexec/**
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          cache: true
      - name: Run toolexec package injection tests
        run: make toolexec-tests
